plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

group = 'io.github.wojciechkoziestanski'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'io.github.palexdev:materialfx:11.13.9'
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    implementation 'com.h2database:h2:2.2.224'
    // Apache PDFBox - w pełni modularna biblioteka do PDF
    implementation 'org.apache.pdfbox:pdfbox:2.0.29'
}

javafx {
    version = "17"
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}

application {
    mainClass = 'io.github.wojciechkoziestanski.UI'
}

test {
    useJUnitPlatform()
}

tasks.withType(JavaCompile) {
    options.compilerArgs += ['--add-reads', 'io.github.wojciechkoziestanski=ALL-UNNAMED']
}

application {
    applicationDefaultJvmArgs = ['--add-reads', 'io.github.wojciechkoziestanski=ALL-UNNAMED']
}